#!/bin/bash
# proxy-lib.sh — raycast-proxy 共用配置与函数（本文件不是 Raycast 命令）
# 改 VM 地址 / 端口 / PAC 地址 / 直连名单，只需要改这里。

PROXY_HOST="${PROXY_HOST:-192.168.64.2}"
HTTP_PORT="${HTTP_PORT:-7890}"     # OpenClash HTTP 端口
SOCKS_PORT="${SOCKS_PORT:-7891}"   # OpenClash SOCKS 端口
PAC_URL="${PAC_URL:-http://192.168.64.2/luci-static/resources/openclash/pac/pac_UFoxsjaWtoYqloow?v=WFwloYjw}"

# 直连名单：内网 / 本地永远不走代理
BYPASS_DOMAINS=("localhost" "127.0.0.1" "*.local" "10.*" "192.168.*" "172.16.*" "169.254/16")

ENV_FILE="$HOME/.config/proxy-env.sh"

# 当前默认路由对应的网络服务名（如 Wi-Fi）
active_service() {
  local iface svc
  iface=$(route -n get default 2>/dev/null | awk '/interface:/{print $2}')
  svc=$(networksetup -listallhardwareports | awk -v dev="$iface" '
    /^Hardware Port:/{ sub(/^Hardware Port: /, ""); port=$0 }
    /^Device:/{ if ($2 == dev) print port }')
  [ -n "$svc" ] && { echo "$svc"; return; }
  echo "Wi-Fi"
}

_is_enabled() { # $1 = networksetup -getxxx 的完整输出
  [ "$(echo "$1" | awk '/^Enabled:/{print $2}')" = "Yes" ]
}

# 输出当前模式：off | global | pac
proxy_state() {
  local s="$1"
  if _is_enabled "$(networksetup -getautoproxyurl "$s" 2>/dev/null)"; then echo pac; return; fi
  if _is_enabled "$(networksetup -getwebproxy "$s" 2>/dev/null)" \
    || _is_enabled "$(networksetup -getsocksfirewallproxy "$s" 2>/dev/null)"; then
    echo global; return
  fi
  echo off
}

proxy_off() {
  local s="$1"
  networksetup -setwebproxystate "$s" off
  networksetup -setsecurewebproxystate "$s" off
  networksetup -setsocksfirewallproxystate "$s" off
  networksetup -setautoproxystate "$s" off
}

proxy_on_global() {
  local s="$1"
  networksetup -setautoproxystate "$s" off
  networksetup -setwebproxy "$s" "$PROXY_HOST" "$HTTP_PORT" off
  networksetup -setsecurewebproxy "$s" "$PROXY_HOST" "$HTTP_PORT" off
  networksetup -setsocksfirewallproxy "$s" "$PROXY_HOST" "$SOCKS_PORT" off
  networksetup -setproxybypassdomains "$s" "${BYPASS_DOMAINS[@]}"
}

proxy_on_pac() {
  local s="$1"
  networksetup -setwebproxystate "$s" off
  networksetup -setsecurewebproxystate "$s" off
  networksetup -setsocksfirewallproxystate "$s" off
  networksetup -setautoproxyurl "$s" "$PAC_URL" on
}

# 主服务是否被 VPN 等抢占（networksetup 无法配置该服务时返回 0）
vpn_primary() {
  local ps
  ps=$(scutil <<<'show State:/Network/Global/IPv4' | awk '/PrimaryService :/{print $3}')
  ! networksetup -getwebproxy "$ps" >/dev/null 2>&1
}

# VM 端口是否可达
proxy_reachable() {
  nc -z -G 2 "$PROXY_HOST" "$HTTP_PORT" 2>/dev/null
}

# 写终端 env 文件；$1 = on|off
write_env_file() {
  mkdir -p "$(dirname "$ENV_FILE")"
  if [ "$1" = "on" ]; then
    cat > "$ENV_FILE" <<EOF
# Generated by raycast-proxy (state: on)
export http_proxy="http://$PROXY_HOST:$HTTP_PORT"
export https_proxy="http://$PROXY_HOST:$HTTP_PORT"
export all_proxy="socks5://$PROXY_HOST:$SOCKS_PORT"
export no_proxy="localhost,127.0.0.1,*.local,10.*,192.168.*,172.16.*"
export HTTP_PROXY="\$http_proxy"
export HTTPS_PROXY="\$https_proxy"
export ALL_PROXY="\$all_proxy"
export NO_PROXY="\$no_proxy"
EOF
  else
    cat > "$ENV_FILE" <<'EOF'
# Generated by raycast-proxy (state: off)
unset http_proxy https_proxy all_proxy no_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
EOF
  fi
}
